const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
const EMPTY_CART = "EMPTY_CART";

module.exports = {
  ADD_TO_CART,
  REMOVE_FROM_CART,
  SAVE_SHIPPING_INFO,
  EMPTY_CART
};
