const NEW_ORDER = {
  NEW_ORDER_REQUEST: "NEW_ORDER_REQUEST",
  NEW_ORDER_SUCCESS: "NEW_ORDER_SUCCESS",
  NEW_ORDER_FAIL: "NEW_ORDER_FAIL"
};

const MY_ORDERS = {
  MY_ORDERS_REQUEST: "MY_ORDERS_REQUEST",
  MY_ORDERS_SUCCESS: "MY_ORDERS_SUCCESS",
  MY_ORDERS_FAIL: "MY_ORDERS_FAIL"
};

const ORDER_DETAILS = {
  ORDER_DETAILS_REQUEST: "ORDER_DETAILS_REQUEST",
  ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS",
  ORDER_DETAILS_FAIL: "ORDER_DETAILS_FAIL"
};

const PAYMENT_STATUS = {
  PAYMENT_STATUS_REQUEST: "PAYMENT_STATUS_REQUEST",
  PAYMENT_STATUS_SUCCESS: "PAYMENT_STATUS_SUCCESS",
  PAYMENT_STATUS_FAIL: "PAYMENT_STATUS_FAIL"
};

const ALL_ORDERS = {
  ALL_ORDERS_REQUEST: "ALL_ORDERS_REQUEST",
  ALL_ORDERS_SUCCESS: "ALL_ORDERS_SUCCESS",
  ALL_ORDERS_FAIL: "ALL_ORDERS_FAIL"
};

const UPDATE_ORDER = {
  UPDATE_ORDER_REQUEST: "UPDATE_ORDER_REQUEST",
  UPDATE_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS",
  UPDATE_ORDER_RESET: "UPDATE_ORDER_RESET",
  UPDATE_ORDER_FAIL:"UPDATE_ORDER_FAIL"
};

const DELETE_ORDER = {
  DELETE_ORDER_REQUEST: "DELETE_ORDER_REQUEST",
  DELETE_ORDER_SUCCESS: "DELETE_ORDER_SUCCESS",
  DELETE_ORDER_RESET: "DELETE_ORDER_RESET",
  DELETE_ORDER_FAIL: "DELETE_ORDER_FAIL"
};

const CLEAR_ERRORS = "CLEAR_ERRORS";

module.exports = {
  NEW_ORDER,
  MY_ORDERS,
  ORDER_DETAILS,
  PAYMENT_STATUS,
  ALL_ORDERS,
  UPDATE_ORDER,
  DELETE_ORDER,
  CLEAR_ERRORS
}