const CLEAR_ERRORS = "CLEAR_ERRORS";

const SLIDER_PRODUCTS = {
  SLIDER_PRODUCTS_REQUEST: "SLIDER_PRODUCTS_REQUEST",
  SLIDER_PRODUCTS_SUCCESS: "SLIDER_PRODUCTS_SUCCESS",
  SLIDER_PRODUCTS_FAIL: "SLIDER_PRODUCTS_FAIL"
};

const NEW_REVIEW = {
  NEW_REVIEW_REQUEST: "NEW_REVIEW_REQUEST",
  NEW_REVIEW_SUCCESS: "NEW_REVIEW_SUCCESS",
  NEW_REVIEW_FAIL: "NEW_REVIEW_FAIL",
  NEW_REVIEW_RESET: "NEW_REVIEW_RESET"
};

const ALL_PRODUCTS = {
  ALL_PRODUCTS_REQUEST: "ALL_PRODUCTS_REQUEST",
  ALL_PRODUCTS_SUCCESS: "ALL_PRODUCTS_SUCCESS",
  ALL_PRODUCTS_FAIL: "ALL_PRODUCTS_FAIL"
};

const DELETE_PRODUCT = {
  DELETE_PRODUCT_RESET: "DELETE_PRODUCT_RESET",
  DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAIL: "DELETE_PRODUCT_FAIL"
};

const NEW_PRODUCT = {
  NEW_PRODUCT_RESET: "NEW_PRODUCT_RESET",
  NEW_PRODUCT_REQUEST: "NEW_PRODUCT_REQUEST",
  NEW_PRODUCT_SUCCESS: "NEW_PRODUCT_SUCCESS",
  NEW_PRODUCT_FAIL: "NEW_PRODUCT_FAIL"
};

const DELETE_REVIEW = {
  DELETE_REVIEW_RESET: "DELETE_REVIEW_RESET",
  DELETE_REVIEW_REQUEST: "DELETE_REVIEW_REQUEST",
  DELETE_REVIEW_SUCCESS: "DELETE_REVIEW_SUCCESS",
  DELETE_REVIEW_FAIL: "DELETE_REVIEW_FAIL"
};

const ADMIN_PRODUCTS = {
  ADMIN_PRODUCTS_REQUEST: "ADMIN_PRODUCTS_REQUEST",
  ADMIN_PRODUCTS_SUCCESS: "ADMIN_PRODUCTS_SUCCESS",
  ADMIN_PRODUCTS_FAIL: "ADMIN_PRODUCTS_FAIL"
};

const PRODUCT_DETAILS = {
  PRODUCT_DETAILS_REQUEST: "PRODUCT_DETAILS_REQUEST",
  PRODUCT_DETAILS_SUCCESS: "PRODUCT_DETAILS_SUCCESS",
  PRODUCT_DETAILS_FAIL: "PRODUCT_DETAILS_FAIL"
};

const REMOVE_PRODUCT_DETAILS = "REMOVE_PRODUCT_DETAILS";

const UPDATE_PRODUCT = {
  UPDATE_PRODUCT_RESET: "UPDATE_PRODUCT_RESET",
  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAIL: "UPDATE_PRODUCT_FAIL"
};

const ALL_REVIEWS = {
  ALL_REVIEWS_REQUEST: "ALL_REVIEWS_REQUEST",
  ALL_REVIEWS_SUCCESS: "ALL_REVIEWS_SUCCESS",
  ALL_REVIEWS_FAIL: "ALL_REVIEWS_FAIL"
}


module.exports = {
  CLEAR_ERRORS,
  SLIDER_PRODUCTS,
  NEW_REVIEW,
  ALL_PRODUCTS,
  DELETE_PRODUCT,
  NEW_PRODUCT,
  DELETE_REVIEW,
  ADMIN_PRODUCTS,
  PRODUCT_DETAILS,
  REMOVE_PRODUCT_DETAILS,
  UPDATE_PRODUCT,
  ALL_REVIEWS
};
