const CLEAR_ERRORS = "CLEAR_ERRORS";

const SLIDER_PRODUCTS = {
  SLIDER_PRODUCTS_REQUEST: "SLIDER_PRODUCTS_REQUEST",
  SLIDER_PRODUCTS_SUCCESS: "SLIDER_PRODUCTS_SUCCESS",
  SLIDER_PRODUCTS_FAIL: "SLIDER_PRODUCTS_FAIL"
};

const NEW_REVIEW = {
  NEW_REVIEW_REQUEST: "NEW_REVIEW_REQUEST",
  NEW_REVIEW_SUCCESS: "NEW_REVIEW_SUCCESS",
  NEW_REVIEW_FAIL: "NEW_REVIEW_FAIL",
  NEW_REVIEW_RESET: "NEW_REVIEW_RESET"
};

const ALL_PRODUCTS = {
  ALL_PRODUCTS_REQUEST: "ALL_PRODUCTS_REQUEST",
  ALL_PRODUCTS_SUCCESS: "ALL_PRODUCTS_SUCCESS",
  ALL_PRODUCTS_FAIL: "ALL_PRODUCTS_FAIL"
};

const DELETE_PRODUCT = {
  DELETE_PRODUCT_RESET: "DELETE_PRODUCT_RESET"
};

const NEW_PRODUCT = {
  NEW_PRODUCT_RESET: "NEW_PRODUCT_RESET"
}

module.exports = {
  CLEAR_ERRORS,
  SLIDER_PRODUCTS,
  NEW_REVIEW,
  ALL_PRODUCTS,
  DELETE_PRODUCT,
  NEW_PRODUCT
}